log:
  level: info
  format: compact

jwt:
  secret: "your_jwt_secret_key"
  expiry: 24

db:
  name: imserver
  host: localhost
  port: 5432
  username: postgres
  password: postgres

redis:
  port: 6379
